services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      NODE_ENV: development
      DATABASE_URL: mysql://techconsult:techconsult@db:3306/techconsult
      VITE_DATABASE_URL: mysql://techconsult:techconsult@db:3306/techconsult
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - app_node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Server=db;Port=3306;Database=techconsult;User=techconsult;Password=techconsult
      MYSQL_SERVER_VERSION: 8.0.36-mysql
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/src
      - dotnet_nuget:/root/.nuget/packages
    working_dir: /src
    command: sh -c "dotnet restore && dotnet watch run --urls http://0.0.0.0:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: techconsult
      MYSQL_USER: techconsult
      MYSQL_PASSWORD: techconsult
      MYSQL_ROOT_PASSWORD: techconsult
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u \"$${MYSQL_USER}\" -p\"$${MYSQL_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  app_node_modules:
  dotnet_nuget:
  mysql_data:
