services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://techconsult:techconsult@db:5432/techconsult
      VITE_DATABASE_URL: postgresql://techconsult:techconsult@db:5432/techconsult
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Host=db;Port=5432;Database=techconsult;Username=techconsult;Password=techconsult
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: techconsult
      POSTGRES_USER: techconsult
      POSTGRES_PASSWORD: techconsult
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techconsult -d techconsult"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  postgres_data:
