services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://techconsult:techconsult@db:3306/techconsult
      VITE_DATABASE_URL: mysql://techconsult:techconsult@db:3306/techconsult
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Server=db;Port=3306;Database=techconsult;User=techconsult;Password=techconsult
      MYSQL_SERVER_VERSION: 8.0.36-mysql
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: techconsult
      MYSQL_USER: techconsult
      MYSQL_PASSWORD: techconsult
      MYSQL_ROOT_PASSWORD: techconsult
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u \"$${MYSQL_USER}\" -p\"$${MYSQL_PASSWORD}\" --silent"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
volumes:
  mysql_data:
