/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TechConsult.Api
 * OpenAPI spec version: 1.0
 */

export type AppointmentType = typeof AppointmentType[keyof typeof AppointmentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppointmentType = {
  AiConsulting: 'AiConsulting',
  WebDevelopment: 'WebDevelopment',
  SaasDevelopment: 'SaasDevelopment',
} as const;
