/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * TechConsult.Api
 * OpenAPI spec version: 1.0
 */

export interface CreateAppointmentRequest {
  /**
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  scheduledAt: string;
  /** @nullable */
  contactEmail?: string | null;
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  notes?: string | null;
  /**
   * @minimum 0
   * @maximum 1440
   */
  duration?: number;
}
